development:
  adapter: postgresql
  encoding: utf8
  username: postgres
  password: 12345678
  database: sslmonitor
  host: localhost
  pool: 30
  timeout: 5000
  port: 5432

production:
  adapter: postgresql
  encoding: utf8
  username: postgres
  password: 12345678
  database: sslmonitor
  host: localhost
  pool: 30
  timeout: 5000
  port: 5432