:verbose: false
:concurrency: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
:timeout: 30
:queues:
  - [low_priority, 1]
  - [high_priority, 2] # high priority
:schedule:
  MonitorJob:
    cron: '*/2 * * * *'
    queue: scheduler
    enabled: true